import Photo from '../../assetsImage/assets/Rectangle_2.png'
import image from '../../assetsImage/assets_transport_vnedorojnaya/TITAN-ATF_DII_1L_1080x1080.png'


const KartochkaTovaraData = [

    //Гидравлические масла

    {
        id: 'renolin_xtreme_temp_32_',
        idName: 'renolin',
        title: 'RENOLIN XTREME TEMP 32',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'Деэмульгирующие гидравлические и смазочные масла рекомендуются для всех видов применения в мобильных гидравлических системах. Они имеют широкий интервал рабочих температур, превосходят требования нового проекта стандарта DIN 51 524-3 (2005 г.) к высокоиндексным маслам класса HVLP и отличаются высокой стабильностью к сдвигу.',
        specifications: ['DIN 51 524-3 (проект 2005 г.): HVLP', 'ISO 6743-4: HV', 'Denison HF0 – T6H20C: гибридные насосы', 'Bosch Rexroth', 'Terex', 'Vickers 35VQ-25: лопастные насосы', ' Vickers V104-C: лопастные насосы', 'US Steel 127,136', 'Cincinnati Milacron P68, P69, P70'],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_100',
        idName: 'renolin',
        title: 'RENOLIN AW 100',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'Масла серии RENOLIN AW производятся на основе высококачественных минеральных базовых масел. Эффективный пакет присадок повышает стойкость масел к окислению и старению, а также обеспечивает превосходную защиту от коррозии (стали и цветных металлов). Синергетическая композиция деактиваторов меди защищает материалы из цветных металлов. Специальные противоизносные цинксодержащие присадки, с мягкими ЕР-свойствами защищают гидронасосы, моторы и другие компоненты системы от износа (при низких и высоких температурах, высоких нагрузках).',
        specifications: ['ISO 6743-4: HM', 'DIN 51 524-2: HLP'],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_100_zaf_hvi',
        idName: 'renolin',
        title: 'RENOLIN AW 100 ZAF HVI',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'RENOLIN AW ZAF HVI – масла с хорошими деэмульгирующими и вязкостно-температурными свойствами для универсального применения в гидравлических системах и редукторах. Могут применяться во всех типах мобильного и стационарного гидравлического оборудования, где рекомендуются гидравлические жидкости класса HVLP DIN 51524-3 (HV ISO 6743-4). RENOLIN AW ZAF HVI могут применяться в гидросистемах металлообрабатывающих станков, термопластавтоматов, мобильной технике и др.',
        specifications: ['ISO 6743-4: HV', 'DIN 51524-3: HVLP'],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_15_hvi',
        idName: 'renolin',
        title: 'RENOLIN AW 15 HVI',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'Работоспособность и надёжность гидравлической системы во многом зависит от качества применяемой рабочей жидкости. Помимо функции передачи значительного количества энергии, гидравлическая жидкость должна уплотнять, охлаждать и смазывать, а также выполнять ряд других функций. При запуске системы излишне вязкая рабочая жидкость поглощает относительно большое количество энергии из-за собственного внутреннего сопротивления. Если жидкость недостаточно вязкая, это может привести к повышенному трению и, как следствие, к быстрому износу. FUCHS разработал серию так называемых «масел низкого трения» ("low friction oils"), которые снижают потери энергии и износ элементов гидросистемы при её пуске. Масла серии RENOLIN AW HVI производятся на базе устойчивых к старению минеральных масел и содержат присадки, дополнительно улучшающие антиокислительные свойства. Продукты этой серии содержат цинк.',
        specifications: ['ISO 6743-4: HV', 'DIN 51 524-3: HVLP', 'ISO 11158'],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_15_zaf_hvi',
        idName: 'renolin',
        title: 'RENOLIN AW 15 ZAF HVI',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'RENOLIN AW ZAF HVI – масла с хорошими деэмульгирующими и вязкостно-температурными свойствами для универсального применения в гидравлических системах и редукторах. Могут применяться во всех типах мобильного и стационарного гидравлического оборудования, где рекомендуются гидравлические жидкости класса HVLP DIN 51524-3 (HV ISO 6743-4). RENOLIN AW ZAF HVI могут применяться в гидросистемах металлообрабатывающих станков, термопластавтоматов, мобильной технике и др.',
        specifications: ['ISO 6743-4: HV', 'DIN 51524-3: HVLP'],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_150',
        idName: 'renolin',
        title: 'RENOLIN AW 150',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'Масла серии RENOLIN AW производятся на основе высококачественных минеральных базовых масел. Эффективный пакет присадок повышает стойкость масел к окислению и старению, а также обеспечивает превосходную защиту от коррозии (стали и цветных металлов).  Синергетическая композиция деактиваторов меди защищает материалы из цветных металлов. Специальные противоизносные цинксодержащие присадки, с мягкими ЕР-свойствами защищают гидронасосы, моторы и другие компоненты системы от износа (при низких и высоких температурах, высоких нагрузках). Масла серии RENOLIN AW относятся к гидравлическим жидкостям на минеральной основе согласно DIN 51524-2 (цинксодержащие, с деэмульгирующими свойствами) и смазочным маслам согласно DIN 51517.',
        specifications: ['ISO 6743-4: HM', 'DIN 51 524-2: HLP'],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_22',
        idName: 'renolin',
        title: 'RENOLIN AW 22',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'Масла серии RENOLIN AW производятся на основе высококачественных минеральных базовых масел. Эффективный пакет присадок повышает стойкость масел к окислению и старению, а также обеспечивает превосходную защиту от коррозии (стали и цветных металлов). Синергетическая композиция деактиваторов меди защищает материалы из цветных металлов. Специальные противоизносные цинксодержащие присадки, с мягкими ЕР-свойствами защищают гидронасосы, моторы и другие компоненты системы от износа (при низких и высоких температурах, высоких нагрузках). Масла серии RENOLIN AW относятся к гидравлическим жидкостям на минеральной основе согласно DIN 51524-2 (цинксодержащие, с деэмульгирующими свойствами) и смазочным маслам согласно DIN 51517.',
        specifications: ['ISO 6743-4: HM', 'DIN 51 524-2: HLP'],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_22_hvi',
        idName: 'renolin',
        title: 'RENOLIN AW 22 HVI',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'Работоспособность и надёжность гидравлической системы во многом зависит от качества применяемой рабочей жидкости. Помимо функции передачи значительного количества энергии, гидравлическая жидкость должна уплотнять, охлаждать и смазывать, а также выполнять ряд других функций. При запуске системы излишне вязкая рабочая жидкость поглощает относительно большое количество энергии из-за собственного внутреннего сопротивления. Если жидкость недостаточно вязкая, это может привести к повышенному трению и, как следствие, к быстрому износу. FUCHS разработал серию так называемых «масел низкого трения» ("low friction oils"), которые снижают потери энергии и износ элементов гидросистемы при её пуске. Масла серии RENOLIN AW HVI производятся на базе устойчивых к старению минеральных масел и содержат присадки, дополнительно улучшающие антиокислительные свойства. Продукты этой серии содержат цинк.',
        specifications: ['ISO 6743-4: HV', 'DIN 51 524-3: HVLP', 'ISO 11158'],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_22_zaf',
        idName: 'renolin',
        title: 'RENOLIN AW 22 ZAF',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'RENOLIN AW ZAF – это серия универсальных беззольных гидравлических жидкостей. RENOLIN AW ZAF производятся из высококачественных минеральных масел в комбинации с эффективными присадками на основе бесцинковых технологий. Продукты RENOLIN AW ZAF обеспечивают надежную защиту компонентов гидравлической системы (моторов, насосов и др.) от износа, а также демонстрируют хорошие антикоррозионные свойства, в том числе по отношению к цветным металлам.',
        specifications: ['ISO 6743-4', 'HM DIN 51 524-2', 'HLP Cincinnati-Milacron P-68, 69, 70 VICKERS M-2950 S'],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_22_zaf_hvi',
        idName: 'renolin',
        title: 'RENOLIN AW 22 ZAF HVI',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'RENOLIN AW ZAF HVI – масла с хорошими деэмульгирующими и вязкостно-температурными свойствами для универсального применения в гидравлических системах и редукторах. Могут применяться во всех типах мобильного и стационарного гидравлического оборудования, где рекомендуются гидравлические жидкости класса HVLP DIN 51524-3 (HV ISO 6743-4). RENOLIN AW ZAF HVI могут применяться в гидросистемах металлообрабатывающих станков, термопластавтоматов, мобильной технике и др',
        specifications: ['ISO 6743-4: HV', 'DIN 51524-3: HVLP', ],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_32',
        idName: 'renolin',
        title: 'RENOLIN AW 32',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'Масла серии RENOLIN AW производятся на основе высококачественных минеральных базовых масел. Эффективный пакет присадок повышает стойкость масел к окислению и старению, а также обеспечивает превосходную защиту от коррозии (стали и цветных металлов). композиция деактиваторов меди защищает материалы из цветных металлов. Специальные противоизносные цинксодержащие присадки, с мягкими ЕР-свойствами защищают гидронасосы, моторы и другие компоненты системы от износа (при низких и высоких температурах, высоких нагрузках). Масла серии RENOLIN AW относятся к гидравлическим жидкостям на минеральной основе согласно DIN 51524-2 (цинксодержащие, с деэмульгирующими свойствами) и смазочным маслам согласно DIN 51517.',
        specifications: ['ISO 6743-4: HM', 'DIN 51 524-2: HLP', ],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_32_hvi',
        idName: 'renolin',
        title: 'RENOLIN AW 32 HVI',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'Работоспособность и надёжность гидравлической системы во многом зависит от качества применяемой рабочей жидкости. Помимо функции передачи значительного количества энергии, гидравлическая жидкость должна уплотнять, охлаждать и смазывать, а также выполнять ряд других функций. При запуске системы излишне вязкая рабочая жидкость поглощает относительно большое количество энергии из-за собственного внутреннего сопротивления. Если жидкость недостаточно вязкая, это может привести к повышенному трению и, как следствие, к быстрому износу. FUCHS разработал серию так называемых «масел низкого трения» ("low friction oils"), которые снижают потери энергии и износ элементов гидросистемы при её пуске. Масла серии RENOLIN AW HVI производятся на базе устойчивых к старению минеральных масел и содержат присадки, дополнительно улучшающие антиокислительные свойства. Продукты этой серии содержат цинк.',
        specifications: ['ISO 6743-4: HV', 'DIN 51 524-3: HVLP', 'ISO 11158' ],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_32_xlt',
        idName: 'renolin',
        title: 'RENOLIN AW 32 XLT',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'RENOLIN AW 32 XLT – это беззольное арктическое гидравлическое масло с превосходными низкотемпературными свойствами. Продукт содержит в своем составе присадки, увеличивающие срок службы масла и повышающие стойкость к старению. Использование RENOLIN AW 32 XLT гарантирует защиту от коррозии стальных деталей и компонентов из цветных металлов в гидравлических системах. Продукт обладает деэмульгирующими свойствами (отделяет воду) и способен работать при очень низких температурах. Полностью соответствует и превосходит требования стандарта DIN 51524-3, HVLP.',
        specifications: ['DIN 51524-3', 'HVLP ISO 6743-4: HV', ],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_32_zaf',
        idName: 'renolin',
        title: 'RENOLIN AW 32 ZAF',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'RENOLIN AW ZAF – это серия универсальных беззольных гидравлических жидкостей. RENOLIN AW ZAF производятся из высококачественных минеральных масел в комбинации с эффективными присадками на основе бесцинковых технологий. Продукты RENOLIN AW ZAF обеспечивают надежную защиту компонентов гидравлической системы (моторов, насосов и др.) от износа, а также демонстрируют хорошие антикоррозионные свойства, в том числе по отношению к цветным металлам.',
        specifications: ['ISO 6743-4', 'HM DIN 51 524-2', ' HLP Cincinnati-Milacron P-68, 69, 70 VICKERS M-2950 S' ],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_32_zaf_hvi',
        idName: 'renolin',
        title: 'RENOLIN AW 32 ZAF HVI',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'RENOLIN AW ZAF HVI – масла с хорошими деэмульгирующими и вязкостно-температурными свойствами для универсального применения в гидравлических системах и редукторах. Могут применяться во всех типах мобильного и стационарного гидравлического оборудования, где рекомендуются гидравлические жидкости класса HVLP DIN 51524-3 (HV ISO 6743-4). RENOLIN AW ZAF HVI могут применяться в гидросистемах металлообрабатывающих станков, термопластавтоматов, мобильной технике и др',
        specifications: ['ISO 6743-4: HV', 'DIN 51524-3: HVLP' ],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_46',
        idName: 'renolin',
        title: 'RENOLIN AW 46',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'Масла серии RENOLIN AW производятся на основе высококачественных минеральных базовых масел. Эффективный пакет присадок повышает стойкость масел к окислению и старению, а также обеспечивает превосходную защиту от коррозии (стали и цветных металлов). Синергетическая композиция деактиваторов меди защищает материалы из цветных металлов. Специальные противоизносные цинксодержащие присадки, с мягкими ЕР-свойствами защищают гидронасосы, моторы и другие компоненты системы от износа (при низких и высоких температурах, высоких нагрузках). Масла серии RENOLIN AW относятся к гидравлическим жидкостям на минеральной основе согласно DIN 51524-2 (цинксодержащие, с деэмульгирующими свойствами) и смазочным маслам согласно DIN 51517.',
        specifications: ['ISO 6743-4: HM', 'DIN 51 524-2: HLP' ],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_46_hvi',
        idName: 'renolin',
        title: 'RENOLIN AW 46 HVI',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'Работоспособность и надёжность гидравлической системы во многом зависит от качества применяемой рабочей жидкости. Помимо функции передачи значительного количества энергии, гидравлическая жидкость должна уплотнять, охлаждать и смазывать, а также выполнять ряд других функций. При запуске системы излишне вязкая рабочая жидкость поглощает относительно большое количество энергии из-за собственного внутреннего сопротивления. Если жидкость недостаточно вязкая, это может привести к повышенному трению и, как следствие, к быстрому износу. FUCHS разработал серию так называемых «масел низкого трения» ("low friction oils"), которые снижают потери энергии и износ элементов гидросистемы при её пуске. Масла серии RENOLIN AW HVI производятся на базе устойчивых к старению минеральных масел и содержат присадки, дополнительно улучшающие антиокислительные свойства. Продукты этой серии содержат цинк.',
        specifications: ['ISO 6743-4: HV', 'DIN 51 524-3: HVLP', 'ISO 11158' ],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_46_zaf',
        idName: 'renolin',
        title: 'RENOLIN AW 46 ZAF',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'RENOLIN AW ZAF – это серия универсальных беззольных гидравлических жидкостей. RENOLIN AW ZAF производятся из высококачественных минеральных масел в комбинации с эффективными присадками на основе бесцинковых технологий. Продукты RENOLIN AW ZAF обеспечивают надежную защиту компонентов гидравлической системы (моторов, насосов и др.) от износа, а также демонстрируют хорошие антикоррозионные свойства, в том числе по отношению к цветным металлам.',
        specifications: ['ISO 6743-4: HM DIN 51 524-2: HLP Cincinnati-Milacron P-68, 69, 70 VICKERS M-2950 S' ],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_68',
        idName: 'renolin',
        title: 'RENOLIN AW 68',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'Масла серии RENOLIN AW производятся на основе высококачественных минеральных базовых масел. Эффективный пакет присадок повышает стойкость масел к окислению и старению, а также обеспечивает превосходную защиту от коррозии (стали и цветных металлов). Синергетическая композиция деактиваторов меди защищает материалы из цветных металлов. Специальные противоизносные цинксодержащие присадки, с мягкими ЕР-свойствами защищают гидронасосы, моторы и другие компоненты системы от износа (при низких и высоких температурах, высоких нагрузках). Масла серии RENOLIN AW относятся к гидравлическим жидкостям на минеральной основе согласно DIN 51524-2 (цинксодержащие, с деэмульгирующими свойствами) и смазочным маслам согласно DIN 51517.',
        specifications: ['ISO 6743-4: HM', 'DIN 51 524-2: HLP' ],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_68_hvi',
        idName: 'renolin',
        title: 'RENOLIN AW 68 HVI',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'Работоспособность и надёжность гидравлической системы во многом зависит от качества применяемой рабочей жидкости. Помимо функции передачи значительного количества энергии, гидравлическая жидкость должна уплотнять, охлаждать и смазывать, а также выполнять ряд других функций. При запуске системы излишне вязкая рабочая жидкость поглощает относительно большое количество энергии из-за собственного внутреннего сопротивления. Если жидкость недостаточно вязкая, это может привести к повышенному трению и, как следствие, к быстрому износу. FUCHS разработал серию так называемых «масел низкого трения» ("low friction oils"), которые снижают потери энергии и износ элементов гидросистемы при её пуске. Масла серии RENOLIN AW HVI производятся на базе устойчивых к старению минеральных масел и содержат присадки, дополнительно улучшающие антиокислительные свойства. Продукты этой серии содержат цинк.',
        specifications: ['ISO 6743-4: HV', 'DIN 51 524-3: HVLP', 'ISO 11158' ],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_68_zaf',
        idName: 'renolin',
        title: 'RENOLIN AW 68 ZAF',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'RENOLIN AW ZAF – это серия универсальных беззольных гидравлических жидкостей. RENOLIN AW ZAF производятся из высококачественных минеральных масел в комбинации с эффективными присадками на основе бесцинковых технологий. Продукты RENOLIN AW ZAF обеспечивают надежную защиту компонентов гидравлической системы (моторов, насосов и др.) от износа, а также демонстрируют хорошие антикоррозионные свойства, в том числе по отношению к цветным металлам.',
        specifications: ['ISO 6743-4: HM DIN 51 524-2: HLP Cincinnati-Milacron P-68, 69, 70 VICKERS M-2950 S' ],
        approvals: [],
        recommendations: [],
        image: image
      },
      {
        id: 'renolin_aw_68_zaf_hvi',
        idName: 'renolin',
        title: 'RENOLIN AW 68 ZAF HVI',
        productid: 'gidravlicheskie_zhidkosti',
        productidName: 'Гидравлические масла',
        category: 'industrial_smasochnie_materials',
        CategoryCatalogNameUrl: 'obsheindustrial_product',
        categoryName: 'Индустриальные смазочные материалы',
        CategoryCatalogName: 'Общеиндустриальные продукты',  
        price: '3000₽',
        description: 'RENOLIN AW ZAF HVI – масла с хорошими деэмульгирующими и вязкостно-температурными свойствами для универсального применения в гидравлических системах и редукторах. Могут применяться во всех типах мобильного и стационарного гидравлического оборудования, где рекомендуются гидравлические жидкости класса HVLP DIN 51524-3 (HV ISO 6743-4). RENOLIN AW ZAF HVI могут применяться в гидросистемах металлообрабатывающих станков, термопластавтоматов, мобильной технике и др',
        specifications: ['ISO 6743-4: HV', 'DIN 51524-3: HVLP' ],
        approvals: [],
        recommendations: [],
        image: image
      },

      //Минеральные редукторные масла

    
    
  ];
export default KartochkaTovaraData;